name: ci

on:
  pull_request:
  workflow_dispatch:
    inputs:
      pr-number:
        description: The number of the pull-request that dispatched the request
        required: true

jobs:
  image:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "${{ github.ref }}"
          echo "${{ inputs.pr-number }}"
