name: ci

on:
  pull_request:
  workflow_call:
    inputs:
      pr:
        required: true
        type: number
      ref:
        required: true
        type: string

jobs:
  image:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "${{ github.ref }}"

      - run: |
          echo "${{ inputs.pr }}"
          echo "${{ inputs.ref }}"
