name: ci

on:
  pull_request:
  workflow_dispatch:
    inputs:
      pull_number:
        description: The number of the pull-request that dispatched the request
        type: number
        required: true

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      statuses: write

    strategy:
      matrix:
        example:
          - one
          - two
          - three

    steps:
      - if: github.event_name == 'workflow_dispatch'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              sha: context.sha,
              context: 'ci / pr-image (${{ matrix.example }})',
              state: 'pending',
              target_url: `${context.payload.repository.html_url}/actions/runs/${context.runId}`
            });

      - run: |
          echo "${{ github.ref }}"
          echo "${{ inputs.pull_number }}"

      - if: always() && github.event_name == 'workflow_dispatch'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              sha: context.sha,
              context: 'ci / pr-image (${{ matrix.example }})',
              state: '${{ job.status }}',
              target_url: `${context.payload.repository.html_url}/actions/runs/${context.runId}`
            });
