name: pr-build

on:
  issue_comment:
    types: [created]

jobs:
  trigger-self:
    # Only run on pull-request comments
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/build-pr-image') }}

    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number

            console.log(`Triggering a build for pull-request ${prNumber}`)
            console.log(context)
            console.log(context.payload.issue.pull_request)

            const ref = `refs/pull/${prNumber}/merge`

            const response = await github.rest.actions.createWorkflowDispatch({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              workflow_id: 'ci.yml',
              ref: 'main'
            })
