name: pr-build

on:
  issue_comment:
    types: [created]

jobs:
  trigger-self:
    # Only run on pull-request comments
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/build-pr-image') }}

    runs-on: ubuntu-latest
    permissions:
      actions: write
      issues: write

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            // Get branch name by pull-request number
            const { data: pr } = await github.rest.pulls.get({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.issue.number
            })

            // Trigger job
            await github.rest.actions.createWorkflowDispatch({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              workflow_id: 'ci.yml',
              ref: pr.head.ref,
              inputs: {
                pull_number: `${context.issue.number}`
              }
            })

            // Update comment indicating job has been dispatched
            await github.rest.reactions.createForIssueComment({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              comment_id: context.payload.comment.id,
              content: rocket
            })
