name: pr-build

on:
  issue_comment:
    types: [created]

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/build-pr-image' }}
    outputs:
      ref: ${{ steps.trigger.outputs.ref }}

    steps:
      - name: Build comment /build-pr-image detected
        id: trigger
        run: |
          ref="refs/pull/${{ github.event.issue.number }}/head"

          echo "Trigger build job for refs/pull/${{ github.event.issue.number }}/head"
          echo ref=$ref >> $GITHUB_OUTPUT
