name: pr-build

on:
  issue_comment:
    types: [created]

jobs:
  trigger:
    # Only run on pull-request comments
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/build-pr-image') }}

    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number
            const { data: pr } = await github.rest.pulls.get({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: prNumber
            })
            branch = pr.head.ref

            console.log(`Triggering a build for pull-request ${prNumber} on branch '${branch}'`)

            const response = await github.rest.actions.createWorkflowDispatch({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              workflow_id: 'ci.yml',
              ref: branch
            })
