name: pr-build

on:
  issue_comment:
    types: [created]

jobs:
  trigger-self:
    runs-on: ubuntu-latest
    # Only run on pull-request comments
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/build-pr-image' }}

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            console.log(context)
            console.log(context.payload.repository.owner)

            const prNumber = context.issue.number
            const ref = `refs/pull/${prNumber}/merge`

            const response = await octokit.rest.actions.createWorkflowDispatch({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              workflow_id: 'ci.yml',
              ref: 'main'
            })
